# Generated by Django 3.0 on 2019-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to='audio')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='UploadTxt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.FileField(upload_to='txt')),
            ],
        ),
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='video')),
            ],
        ),
    ]
