# Generated by Django 3.0 on 2020-01-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentAnalysis', '0008_auto_20191227_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
